### ISSUE TITLE
Overlay and Witcher 2

### ISSUE THREAD

**Issue by MartinPL** [nickguletskii/GLXOSD#105]
Game have launcher so need to run by terminal

Run command:
> glxosd --steam ./witcher2

Error:
> ERROR: ld.so: object 'libglxosd-glinject.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored

OS: Antergos / Arch; OSD working, tested in DotA 2

**Comment by licaon-kter** [comment]
Not an actual error (you can ignore that message), but Witcher 2 is 32 bit so you need glxosd 32bit libs too.

**Comment by MartinPL** [comment]
Thanks for replay.
Yes you have right, just installed [glxosd32](https://gist.github.com/Phitherek/cb5d7ab05520914e4e37d0ca7ac840ba) and it works ;)
