### ISSUE TITLE
Overlay corruption

### ISSUE THREAD

**Issue by wheybags** [nickguletskii/GLXOSD#19]
Hi, on my system (debian sid), when using this with https://github.com/wheybags/freeablo/ , I get the following instead of a clean display:
![screenshot from 2015-02-15 23 54 27](https://cloud.githubusercontent.com/assets/1093274/6205677/bd890bc6-b56e-11e4-9237-10808f21ea26.png)
The application uses SDL2.
It worked fine on glxgears.

**Comment by nickguletskii** [comment]
Do I need to have Diablo to replicate this issue?

**Comment by wheybags** [comment]
To run freeablo you do, yeah :s. I'll see if I can make a minimal example.

**Comment by nickguletskii** [comment]
Before you waste more of your time helping me, let me just read some freeablo sourcecode and see if I can come up with a blind fix.

**Comment by nickguletskii** [comment]
Version 2.4.0 may fix this, but I can't confirm this because I don't have freablo.

**Comment by wheybags** [comment]
nope, but it is a bit better :p

![screenshot from 2015-09-02 23-26-06](https://cloud.githubusercontent.com/assets/1093274/9646291/29fd6ff2-51ca-11e5-93e7-40800165ff00.png)

**Comment by wheybags** [comment]
Sorry, never noticed you asking what display drivers I use, nvidia proprietary drivers, version 340.76

**Comment by nickguletskii** [comment]
Thanks, I will try to find the cause using a different application that uses Rocket as its engine when I'll have the time. Sorry for the inconvenience.

**Comment by scrawl** [comment]
I have a similar looking corruption in XCOM: Enemy Unknown. The funny thing is, "Gathering data..." text rendered correctly, then when it gets to showing FPS numbers, most glyphs are corrupted... but not the characters that are included in the "gathering data" string!

![glxosd_xcom](https://cloud.githubusercontent.com/assets/720642/9707255/d83bf644-5501-11e5-8d1e-da9199ac8d23.png)

**Comment by scrawl** [comment]
Also, glxosd appears to be corrupting the game's textures, in particular the intro videos:

![glxosd_intro](https://cloud.githubusercontent.com/assets/720642/9707284/c3c1e664-5502-11e5-89ac-c3073dad23b6.png)

Everything looks fine when not launched through glxosd.

I'm using the latest master branch.

**Comment by scrawl** [comment]
> Also, glxosd appears to be corrupting the game's textures, in particular the intro videos:

Fixed by PR #50. The corrupted overlay is still unfixed, though.

**Comment by scrawl** [comment]
> The corrupted overlay is still unfixed, though.

I think I've fixed it. The glPixelStore modes weren't being reset. Pull request incoming...

"glPixelStore sets pixel storage modes that affect the operation of subsequent glReadPixels as well as the unpacking of texture patterns (see ... *glTexImage2D*, ...).

**Comment by scrawl** [comment]
https://www.opengl.org/sdk/docs/man/html/glPixelStore.xhtml

" Six more affect the unpacking of pixel data from memory: GL_UNPACK_SWAP_BYTES, GL_UNPACK_LSB_FIRST, GL_UNPACK_ROW_LENGTH, GL_UNPACK_IMAGE_HEIGHT, GL_UNPACK_SKIP_PIXELS, GL_UNPACK_SKIP_ROWS, GL_UNPACK_SKIP_IMAGES, and GL_UNPACK_ALIGNMENT."

Six? I count eight. :D

**Comment by scrawl** [comment]
Should be fixed by PR #51. @wheybags: Please test if freeablo is fixed!

**Comment by wheybags** [comment]
Yup, works perfectly.
Thanks scrawl!
