### ISSUE TITLE
Toggle overlay between different corners of the screen?

### ISSUE THREAD

**Issue by tgharib** [nickguletskii/GLXOSD#22]
By default, it is in the top-left corner. Maybe have a button so that it can be moved to the bottom-right, top-right, or bottom-left corners?

**Comment by myromance123** [comment]
While there's no shortcut for this, you can edit the configuration text file to change the position of the text. This is how I do it on Ubuntu. Open a Terminal, enter the following:
```bash
sudo gedit /etc/glxosd.conf
```
<a href="http://imgur.com/U7fHOhF"><img src="http://i.imgur.com/U7fHOhF.png" title="source: imgur.com" /></a>

So, I've got it open in Gedit and I just head to lines 52 and 53.
<a href="http://imgur.com/V0dQn9f"><img src="http://i.imgur.com/V0dQn9f.png" title="source: imgur.com" /></a>

I don't change it drastically, but you could change the values to put it absolutely anywhere on your screen. I like to adjust it further down and slightly more to the right, so this is what it usually looks like for me after I've changed the values:
<a href="http://imgur.com/p4MFJs2"><img src="http://i.imgur.com/p4MFJs2.png" title="source: imgur.com" /></a>

The beauty of the configuration text file is that you have absolute control on where it appears on the screen, at what size, what font, what color and outline and a whole lot more :)

**Comment by nickguletskii** [comment]
GLXOSD v3 can be configured to align to any of the 4 corners.
