### ISSUE TITLE
Compatibility Issue with Unity framework

### ISSUE THREAD

**Issue by DistantThunder** [nickguletskii/GLXOSD#26]
It appears there's a consistent compatibility issue with recent Unity (perhaps from version 5?) based games and GLXOSD:
I mainly tested on the many available Kickstarter Demo out there and I have been having consistent crashes aka *(core dumped)"$@"*  whether using 32 or 64 bit binaries of games with the corresponding GLXOSD libraries.

My setup: 

* Arch Linux - 3.19.2-1-ARCH / Ubuntu 14.04.2 LTS (3.19-pf-kernel)
* Gnome Shell - 3.14.3 / Unity 
* NVIDIA 346.47 (and versions before)

Tested on:

> https://roystanross.wordpress.com/super-mario-64-hd/
> https://www.kickstarter.com/projects/kavagamestudio/call-of-combat/
Among others.

**Comment by nickguletskii** [comment]
It's likely that this issue is caused by libstdc++ being bundled with Unity. Please see [the according FAQ entry](http://glxosd.nickguletskii.com/faq.html#when-i-launch-an-application-with-glxosd-it-crashes-why).

If that is not the issue, please ask for this issue to be reopened.

**Comment by nickguletskii** [comment]
This seems to be fixed by version 3.

**Comment by DistantThunder** [comment]
Alright then, thanks!
