### ISSUE TITLE
Unable to tune OSD's info

### ISSUE THREAD

**Issue by DistantThunder** [nickguletskii/GLXOSD#27]
Hello. I'm running Arch Linux and using glxosd from git.

It appears no matter what I comment out in the config file, I can't modify the information displayed on the OSD. I always get the "full" report, and I can't seem to filter or tune it, though I've seen other people being able to display only FPS or such things.

I'm running " r32.9f216b2-1". 

Thanks !

**Comment by nickguletskii** [comment]
Commenting out lines in the configuration file won't help. To hide some info, replace the format string with whitespace. Related issue: https://github.com/nickguletskii/GLXOSD/issues/28

**Comment by DistantThunder** [comment]
@nickguletskii 
I just achieved what I wished by using regexes with the "libsensors_chip_filter" parameter, but I'll remember what you linked to, thanks.

**Comment by nickguletskii** [comment]
This is (hopefully) fixed in version 2.4.0.
