### ISSUE TITLE
GLXOSD may be incompatible with applications using freetype

### ISSUE THREAD

**Issue by scrawl** [nickguletskii/GLXOSD#37]
Via https://github.com/nickguletskii/GLXOSD/issues/33#issuecomment-138097857

GLXOSD uses freetype at runtime, which can conflict if the application is using a different version of freetype.

A couple fix ideas:

* Linking freetype statically: that wouldn't help, right?
* Use freetype once on startup, then shut it down when we're done and before Dota FT_Init's its freetype. I think this would avoid the conflicts, but we'd need to know all glyphs needed for the OSD in advance.
* Outsource the font rendering code to a separate executable (either called at runtime, or called when installing GLXOSD, generating a bitmap font)
* Don't use freetype

**Comment by nickguletskii** [comment]
This issue is weird. It's not a linking problem, unlike the libstdc++ problem. The weird part about this is that FT_Libraries should be independent.

I will have to have a deeper look before deciding what to do.

**Comment by nickguletskii** [comment]
This is ridiculous! Steam Runtime contains libfreetype 2.4.8, which is **4 years old**!!! No wonder it doesn't work... I'll have to go over the commits to the affected functions and work around all the bugs present in old freetype...

**Comment by nickguletskii** [comment]
This should be fixed in 3.1.0.
