### ISSUE TITLE
Civilization 5 segfaults on start

### ISSUE THREAD

**Issue by scrawl** [nickguletskii/GLXOSD#45]
Using the latest GLXOSD version from the PPA on Ubuntu 14.04, 64 bit. Civ5 appears to be a 32 bit game.

<pre>
/usr/bin/glxosd /home/scrawl/Steam/ubuntu12_32/steam-runtime/run.sh gdb ./Civ5XP 
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Civ5XP...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/scrawl/Steam/SteamApps/common/Sid Meier's Civilization V/Civ5XP 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
warning: the debug information found in "./libopenal.so.1.13.0" does not match "./libopenal.so.1" (CRC mismatch).

warning: the debug information found in "./libuuid.so.1.3.0" does not match "./libuuid.so.1" (CRC mismatch).

[New Thread 0xf5019b40 (LWP 7576)]
[GLXOSD] Reading global configuration file at "/etc/glxosd.conf"...
[GLXOSD] Found key-value pair: (key: "font_name", value: "CPMono_v07 Bold")
[GLXOSD] Found key-value pair: (key: "font_size_int", value: "16")
[GLXOSD] Found key-value pair: (key: "font_colour_r_int", value: "255")
[GLXOSD] Found key-value pair: (key: "font_colour_g_int", value: "0")
[GLXOSD] Found key-value pair: (key: "font_colour_b_int", value: "255")
[GLXOSD] Found key-value pair: (key: "font_colour_a_int", value: "255")
[GLXOSD] Found key-value pair: (key: "font_outline_colour_r_int", value: "0")
[GLXOSD] Found key-value pair: (key: "font_outline_colour_g_int", value: "0")
[GLXOSD] Found key-value pair: (key: "font_outline_colour_b_int", value: "0")
[GLXOSD] Found key-value pair: (key: "font_outline_colour_a_int", value: "255")
[GLXOSD] Found key-value pair: (key: "font_outline_width_float", value: "1")
[GLXOSD] Found key-value pair: (key: "show_text_outline_bool", value: "true")
[GLXOSD] Found key-value pair: (key: "text_pos_x_int", value: "4")
[GLXOSD] Found key-value pair: (key: "text_pos_y_int", value: "4")
[GLXOSD] Found key-value pair: (key: "text_spacing_x_float", value: "0")
[GLXOSD] Found key-value pair: (key: "text_spacing_y_float", value: "0")
[GLXOSD] Found key-value pair: (key: "osd_toggle_keycombo", value: "Shift+F10")
[GLXOSD] Found key-value pair: (key: "vsync_toggle_keycombo", value: "Shift+F11")
[GLXOSD] Found key-value pair: (key: "frame_logging_toggle_keycombo", value: "Shift+F9")
[GLXOSD] Found key-value pair: (key: "frame_log_keep_in_memory_bool", value: "false")
[GLXOSD] Found key-value pair: (key: "frame_logging_message_string", value: "Logging frame timings...")
[GLXOSD] Found key-value pair: (key: "frame_logging_dump_in_progress_message_string", value: "frame_logging_dump_in_progress_message_string")
[GLXOSD] Found key-value pair: (key: "frame_log_directory_string", value: "/tmp/")
[GLXOSD] Found key-value pair: (key: "frame_logging_duration_ms", value: "0")
[GLXOSD] Found key-value pair: (key: "fps_format", value: "FPS: %1$.1f\n")
[GLXOSD] Found key-value pair: (key: "temperature_format", value: "%1$.0f C")
[GLXOSD] Found key-value pair: (key: "libsensors_chip_format", value: "%1%:\n")
[GLXOSD] Found key-value pair: (key: "libsensors_chip_feature_format", value: " %1%: %2%\n")
[GLXOSD] Found key-value pair: (key: "libsensors_chip_filter", value: "NULL")
[GLXOSD] Found key-value pair: (key: "libsensors_chip_feature_filter", value: "NULL")
[GLXOSD] Found key-value pair: (key: "nvidia_gpu_format", value: "%1% (%2%): %3%\n")
[GLXOSD] The configuration was read successfully.
[GLXOSD] Reading user's configuration file at "/home/scrawl/.config/glxosd/glxosd.conf"...
[GLXOSD] Found key-value pair: (key: "osd_toggle_keycombo", value: "Shift+F9")
[GLXOSD] The configuration was read successfully.
[GLXOSD] Loading libglxosd-plugins-libsensors-support.so
[GLXOSD] Loaded libglxosd-plugins-libsensors-support.so
[New Thread 0xf3d3db40 (LWP 7577)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xf3d3db40 (LWP 7577)]
0xf77f112c in glGetIntegerv () from /usr/lib32/nvidia-352/libGL.so.1
(gdb) bt
#0  0xf77f112c in glGetIntegerv () from /usr/lib32/nvidia-352/libGL.so.1
#1  0xf7fbbf68 in glGetIntegerv () from /usr//lib/i386-linux-gnu//glxosd/libglxosd-glinject.so
#2  0x090609f2 in SDL_GL_GetAttribute ()
#3  0x0864ad24 in ASL::SDL::CreateContext(SDL_Window*, int, int, int, bool) ()
#4  0x0863e68e in CASLDisplayDeviceList::CASLDisplayDeviceList() ()
#5  0x0863e5d5 in CASLDisplayDeviceList::Instance() ()
#6  0x0858205e in IDirect3D_Mac::IDirect3D_Mac() ()
#7  0x085920bd in Direct3DCreate9 ()
#8  0x08d108d1 in FireGrafix::Enum32BitDisplayModes() ()
#9  0x086e16f9 in Civ5App::Init(char const*) ()
#10 0x0865b3ed in WinMain ()
#11 0x085f5487 in ?? ()
#12 0x085d8e3e in ThreadHANDLE::ThreadProc(void*) ()
#13 0xf7acaf70 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#14 0xf792ebee in clone () from /lib/i386-linux-gnu/libc.so.6
(gdb) 
</pre>

<pre>
(gdb) info shared
From        To          Syms Read   Shared Object Library
0xf7fdc860  0xf7ff47ac  Yes (*)     /lib/ld-linux.so.2
0xf7fd2900  0xf7fd3724  Yes (*)     /usr//lib/i386-linux-gnu//glxosd/libglxosd-elfhacks.so
0xf7fb35f0  0xf7fc75d4  Yes (*)     /usr//lib/i386-linux-gnu//glxosd/libglxosd-glinject.so
0xf7f37a70  0xf7f7c4a4  Yes (*)     /usr//lib/i386-linux-gnu//glxosd/libglxosd.so
0xf7d7f1c0  0xf7e7f618  Yes (*)     ./libcrypto.so.1.0.0
0xf7cd1b60  0xf7d251a8  Yes (*)     ./libMiles.so
0xf7c95a90  0xf7cadc54  Yes         ./libtbb.so.2
0xf7c41e00  0xf7c79348  Yes (*)     ./libssl.so.1.0.0
0xf7b141e0  0xf7ba2948  Yes (*)     /home/scrawl/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libX11.so.6
0xf7ac8840  0xf7ad54a7  Yes (*)     /lib/i386-linux-gnu/libpthread.so.0
0xf7abb9b0  0xf7abf0ca  Yes (*)     /lib/i386-linux-gnu/librt.so.1
0xf7a3a9a0  0xf7a9e458  Yes (*)     ./libc++.so.1
0xf79f6450  0xf7a06d88  Yes (*)     ./libcxxrt.so
0xf785a420  0xf798bb6e  Yes (*)     /lib/i386-linux-gnu/libc.so.6
0xf7835820  0xf783d848  Yes (*)     ./libsteam_api.so
0xf7777d20  0xf77e33ad  Yes (*)     /usr/lib32/nvidia-352/libGL.so.1
0xf76e7e20  0xf7720fc8  Yes (*)     ./libopenal.so.1
0xf76dfad0  0xf76e096c  Yes (*)     /lib/i386-linux-gnu/libdl.so.2
0xf769d600  0xf76cb70b  Yes (*)     /lib/i386-linux-gnu/libm.so.6
0xf76800a0  0xf7693c64  Yes (*)     /home/scrawl/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libgcc_s.so.1
0xf7677fb0  0xf7679c28  Yes (*)     ./libuuid.so.1
---Type <return> to continue, or q <return> to quit---
0xf7594180  0xf75a80e8  Yes         ./libiconv.so.2
0xf74f07a0  0xf755d254  Yes (*)     /home/scrawl/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6
0xf74157d0  0xf74819d8  Yes (*)     /home/scrawl/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libfreetype.so.6
0xf73de070  0xf73f9298  Yes (*)     /home/scrawl/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libfontconfig.so.1
0xf73c5760  0xf73d2668  Yes (*)     /home/scrawl/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libz.so.1
0xf73a9d20  0xf73ba838  Yes (*)     /home/scrawl/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libxcb.so.1
0xf739dec0  0xf739fb03  Yes (*)     /usr/lib32/nvidia-352/tls/libnvidia-tls.so.352.41
0xf5793a00  0xf68f0b00  Yes (*)     /usr/lib32/nvidia-352/libnvidia-glcore.so.352.41
0xf51bd730  0xf51c7df8  Yes (*)     /home/scrawl/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libXext.so.6
0xf5193020  0xf51ac828  Yes (*)     /home/scrawl/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libexpat.so.1
0xf518d9e0  0xf518e828  Yes (*)     /home/scrawl/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libXau.so.6
0xf5186d00  0xf51889a8  Yes (*)     /home/scrawl/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libXdmcp.so.6
0xf504ce70  0xf50518e3  Yes (*)     /lib/i386-linux-gnu/libnss_compat.so.2
0xf50361d0  0xf50427e3  Yes (*)     /lib/i386-linux-gnu/libnsl.so.1
0xf50289e0  0xf502edef  Yes (*)     /lib/i386-linux-gnu/libnss_nis.so.2
0xf501bad0  0xf50226bb  Yes (*)     /lib/i386-linux-gnu/libnss_files.so.2
0xf7af9ae0  0xf7afee58  Yes (*)     /home/scrawl/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libXcursor.so.1
0xf7aef320  0xf7af50f8  Yes (*)     /home/scrawl/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libXrender.so.1
0xf7ae8fa0  0xf7aeb708  Yes (*)     /home/scrawl/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libXfixes.so.3
0xf7ae47a0  0xf7ae5188  Yes (*)     /home/scrawl/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libXinerama.so.1
0xf4809900  0xf48144e8  Yes (*)     /home/scrawl/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libXi.so.6
0xf4800130  0xf48049c8  Yes (*)     /home/scrawl/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libXrandr.so.2
---Type <return> to continue, or q <return> to quit---
0xf47f9b20  0xf47fc558  Yes (*)     /home/scrawl/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libXxf86vm.so.1
0xf411f230  0xf4149d64  Yes (*)     /usr//lib/i386-linux-gnu//glxosd/libglxosd-plugins-libsensors-support.so
0xf40af480  0xf40b5964  Yes (*)     /usr/lib/i386-linux-gnu/libsensors.so.4
(*): Shared library is missing debugging information.
</pre>

**Comment by nickguletskii** [comment]
That's weird... It used to work perfectly, and Civ 5 was one of the games I actually tested against. The backtrace is even weirder...
