### ISSUE TITLE
drawableHandlers not thread safe

### ISSUE THREAD

**Issue by scrawl** [nickguletskii/GLXOSD#47]
This is a theoretical issue that I haven't seen in practice, but still worth fixing?

In particular, this code:

<pre>
void GLXOSD::osdHandleBufferSwap(Display* display, GLXDrawable drawable) {
...
	if (osdVisible && display && drawable) {

		auto it = drawableHandlers->find(glXGetCurrentContext());

		OSDInstance* instance;

		if (it == drawableHandlers->end()) {
			instance = new OSDInstance();
			drawableHandlers->insert(
					std::pair<GLXContext, glxosd::OSDInstance*>(
							glXGetCurrentContext(), instance));
		} else {
			instance = (*it).second;
</pre>

glXSwapBuffers can be called from multiple threads at the same time, if they are using independent contexts. The use of drawableHandlers map isn't thread safe, inserting an element there while another thread is iterating (find) on the map will likely crash.

**Comment by nickguletskii** [comment]
Thank you. You are right, this issue must be fixed. It may also cause corruption in some cases.

**Comment by nickguletskii** [comment]
Should be fixed in 2.5.0.
