### ISSUE TITLE
symbol lookup error: /usr/lib/x86_64-linux-gnu/glxosd/libglxosd-plugins-nvidia-support.so: undefined symbol: XextFindDisplay

### ISSUE THREAD

**Issue by jonchampagne** [nickguletskii/GLXOSD#5]
Running glxosd with the nvidia 337.25 drivers via optimus/primus. Crashes immediately. Output from all varations of primusrun/optirun is the same.

$ primusrun glxosd glxgears
[GLXOSD] Loading libglxosd-plugins-libsensors-support.so
[GLXOSD] Loaded libglxosd-plugins-libsensors-support.so
[GLXOSD] Loading libglxosd-plugins-nvidia-support.so
[GLXOSD] Loaded libglxosd-plugins-nvidia-support.so
glxgears: symbol lookup error: /usr/lib/x86_64-linux-gnu/glxosd/libglxosd-plugins-nvidia-support.so: undefined symbol: XextFindDisplay

Not sure whether the program needs to be updated the newer drivers, or if it's a problem with bumblebee, but figured i'd mention it here.

**Comment by nickguletskii** [comment]
GLXOSD v3 potentially fixes the problem. I would be very grateful if anyone could confirm one way or another.

**Comment by nickguletskii** [comment]
XextFindDisplay is no longer used in version 3, therefore this issue is obsolete.

**Comment by Yaksinikos** [comment]
> XextFindDisplay is no longer used in version 3, therefore this issue is obsolete.

But it still do not work.
v. glxosd  3.2.2-1

$ glxosd primusrun ./start.sh
/bin/bash: symbol lookup error: /usr//lib//glxosd/libglxosd-glinject.so: undefined symbol: XLookupKeysym
$ primusrun glxosd ./start.sh
/bin/bash: symbol lookup error: /usr//lib//glxosd/libglxosd-glinject.so: undefined symbol: XLookupKeysym
$ glxosd optirun ./start.sh
optirun: symbol lookup error: /usr//lib//glxosd/libglxosd-glinject.so: undefined symbol: XLookupKeysym
$ glxosd optirun ./start.sh
optirun: symbol lookup error: /usr//lib//glxosd/libglxosd-glinject.so: undefined symbol: XLookupKeysym
