### ISSUE TITLE
Missing characters and crash in Factorio

### ISSUE THREAD

**Issue by thesbros** [nickguletskii/GLXOSD#54]
In [Factorio](http://factorio.com), some characters in the GUI are missing when using GLXOSD.

Without GLXOSD:
![](https://i.imgur.com/tL7AJxD.png)

With GLXOSD:
![](https://i.imgur.com/kYl87uP.png)

It seems to be random every time I start it up which characters are missing. The game also crashes when loading a save with GLXOSD. May be related to #33 / #37.

The segfault doesn't seem to give much information:
```c
Factorio crashed. Generating symbolized stacktrace, please wait ...
#0  0x7f264ffb0680 in ?? at ??:0
#1  0x7f26500a5195 in ?? at ??:0
#2  0xb2742e in ?? at ??:0
#3  0xb94572 in ?? at ??:0
#4  0xb2bbf3 in ?? at ??:0
#5  0x521ae2 in ?? at ??:0
#6  0xa181d6 in ?? at ??:0
#7  0xa19aee in ?? at ??:0
#8  0xa1bbbf in ?? at ??:0
#9  0xa6dc9a in ?? at ??:0
#10 0x7f264ff9d610 in ?? at ??:0
#11 0x40a379 in ?? at ??:0
```

Using the 64-bit version of Factorio 0.12.8 and GLXOSD 2.3.3, also happens with 2.5.0.

**Comment by nickguletskii** [comment]
Like with other games which had issues with text corruption previously, the issue should be fixed with GLXOSD v3. Don't hesitate to comment if that isn't the case.
