### ISSUE TITLE
GLXOSD support on Steam OS

### ISSUE THREAD

**Issue by ganeshams** [nickguletskii/GLXOSD#55]
Will GLXOSD work on Steam OS. If yes, please provide any links/document to install. 
I installed SteamOS 1.0 on AMD system. Followed the document "http://glxosd.nickguletskii.com/usage.html#steam-games" but could not launch the games after that. i had to remove "glxosd --steam %command%" to make the game run again

**Comment by nickguletskii** [comment]
I'll start setting up a repository for Debian once I have the time. I don't have any time estimates right now, but I am hoping that it will be soon.

**Comment by nickguletskii** [comment]
GLXOSD is now packaged for Debian jessie, stretch and sid. For distributions based on Debian, please follow the [installation instructions for Debian derivatives](https://glxosd.nickguletskii.com/install/#debian-other).
