### ISSUE TITLE
Add support for custom commands

### ISSUE THREAD

**Issue by Xaero252** [nickguletskii/GLXOSD#56]
This would allow a user to tailor the output of GLXOSD to their specific needs, line-by-line if they so chose. For example, one could have a `~/.glxosdrc` file and specify the output of glxosd based on that similar to conky, by using individual shell commands and displaying the STDOUT from those commands.

**Comment by nickguletskii** [comment]
I'll implement this once I get the chance. It's something that I had on my mind for a long time.

**Comment by nickguletskii** [comment]
GLXOSD v3 has a plugin API. There isn't much documentation yet, but stay tuned for more information.
