### ISSUE TITLE
Black boxes instead of FPS text in Alien Isolation

### ISSUE THREAD

**Issue by myromance123** [nickguletskii/GLXOSD#57]
Hi, it looks like the black boxes issues as seen in #18 is back for some reason.

Running on Ubuntu 15.10 64bit with a GTX 680 on Nvidia 355.11 drivers, this is what I see in Alien Isolation with GLXOSD:
<a href="http://imgur.com/3fBh2YR"><img src="http://i.imgur.com/3fBh2YR.png" title="source: imgur.com" /></a>

**Comment by scrawl** [comment]
Now that I have the game, I took a quick look at this issue.

The issue was GLXOSD not resetting the GL_PIXEL_UNPACK_BUFFER before uploading textures. Will open a pull request in a second to fix this.

**Comment by scrawl** [comment]
Works now.

![glxosd_alienisolation](https://cloud.githubusercontent.com/assets/720642/12936633/988792d2-cfa0-11e5-86f3-30f8f038ecf2.png)
