### ISSUE TITLE
Counter Strike Source runs like crap

### ISSUE THREAD

**Issue by ExplosiveSilo** [nickguletskii/GLXOSD#58]
When I had GLXOSD running while I played Counter Strike Source, the game ran like crap.
It had 13fps, no matter what I did, it never changed, not even when I changed it from High to Low, even the screen resolution from 1920x1080 to 1280x720.

It was working fine in CSGO and Duke Nukem 3D so I didn't know it was GLXOSD until I decided to try removing it from the command line.

Now my theory is that GLXOSD is capping the game at 13fps. Cause not once did I ever see it go above 13 (except for like 13.7 and that stuff), never 14 or above.
It went below, never above.

**Comment by licaon-kter** [comment]
You glxosd conf?

**Comment by ExplosiveSilo** [comment]
What do you mean?

**Comment by ExplosiveSilo** [comment]
My GLXOSD conf is the default one, I just downloaded it and installed it and shoved the steam argument into the command line like it said in the site.

**Comment by nickguletskii** [comment]
Can you please provide me with the following information? Thank you.

* Your distribution (name and version)
* GPU driver (please mention if you have hybrid graphics)

**Comment by ExplosiveSilo** [comment]
Linux Mint 17, XFCE
R9 270x AMD
FGLRX-Updates
Version: 2:15.200-0ubuntu0.5
Not sure if that's a hybrid, I doubt it but better safe than sorry.

**Comment by nickguletskii** [comment]
Version 3 should fix the performance issues. If the issue persists, please create a new issue.
