### ISSUE TITLE
Crashing Thea

### ISSUE THREAD

**Issue by licaon-kter** [nickguletskii/GLXOSD#59]
Download Thea from here: https://steamcommunity.com/app/378720/discussions/0/490125737485986607

Running Thea.x86_64 w/ glxosd = crash

**Comment by licaon-kter** [comment]
Crashing with 3.0.2 too.

**Comment by nickguletskii** [comment]
Thank you. I fixed the issue in v3.0.3.

**Comment by licaon-kter** [comment]
Yes.
