### ISSUE TITLE
Missing graphics in Divinity: Original Sin Enhanced Edition

### ISSUE THREAD

**Issue by licaon-kter** [nickguletskii/GLXOSD#60]
Proof: https://i.imgur.com/rwEecZk.jpg

Without GLXOSD:
* there is a dropdown icon near resolution, like above for monitor or below for display mode
* there is a checkbox for Frame Cap Enable
* slider for frame cap does not disappear when hoovered
* buttons like Default or Apply don't disappear leaving only text when hoovered

**Comment by nickguletskii** [comment]
Could you please confirm that this is still the case with GLXOSD v3?

**Comment by licaon-kter** [comment]
Fixed in v3
