### ISSUE TITLE
Team Fortress 2 Not Starting

### ISSUE THREAD

**Issue by KovacsA22** [nickguletskii/GLXOSD#61]
I cant start Team Fortress 2 with glxosd. When I edited the launch options the game doesn't start and when I tried starting it with the command line there is no overlay.

**Comment by licaon-kter** [comment]
Output on terminal start?

Use https://gist.github.com to paste.

**Comment by KovacsA22** [comment]
Some strange stuff mainly

```
pid 6562 != 6559, skipping destruction (fork without exec?)
Running Steam on ubuntu 15.10 64-bit
STEAM_RUNTIME is enabled automatically
```

then stops

https://gist.github.com/KovacsA22/cf13dcd7d5146129451c

**Comment by KovacsA22** [comment]
Anyways the glxgears doesn't even work. This project has been abandoned very much :(
But I need an fps monitoring software :(

**Comment by licaon-kter** [comment]
Works on glxgears here ok, so maybe your system has another issue?!

Did you install both 32 and 64 bit libs?

**Comment by nickguletskii** [comment]
Can you please provide me with the following information? Thank you.

* Your distribution (name and version)
* GPU driver (please mention if you have hybrid graphics)
* Method of installation
* If you are building GLXOSD from source, what version of GCC are you using? Is it different from the one that was used to build glxgears?

**Comment by KovacsA22** [comment]
Ubuntu 15.10 64-bit
I have integrated intel graphics chip on a laptop.
I have installed both intel drivers (01.org) and oibaf's drivers
I tried compiling the 32 bit, 64 bit in every combination

I want to use this to do some statistical measures on my fps with different cpu configurations: min,max,avg fps.

**Comment by nickguletskii** [comment]
I have a feeling that this has to do with these weird drivers you are running. As far as I know, Intel graphics drivers come with the kernel.

Also, please provide me with the output of `glxinfo`. It could be that your graphics chip doesn't support OpenGL 3.

**Comment by licaon-kter** [comment]
@KovacsA22 is the PPA not working on your distro?

**Comment by KovacsA22** [comment]
oh I found something

https://gist.github.com/KovacsA22/9f6b6e6c3282afa2c78f

**Comment by nickguletskii** [comment]
Yep, this means that your graphics chip doesn't support the OpenGL version GLXOSD needs.
