### ISSUE TITLE
add installation instructions for Fedora and Arch

### ISSUE THREAD

**Issue by kparal** [nickguletskii/GLXOSD#66]
I have packaged glxosd for Fedora in a COPR repo (analogous to PPA repos in Ubuntu), and I'm going to maintain it. It's available here:
https://copr.fedorainfracloud.org/coprs/kparal/glxosd/

If you could link to it from https://glxosd.nickguletskii.com/install.html , I believe that could attract more users (esp. those not willing to compile it by hand). All the installation instructions are on the COPR page, so just a link is enough, I believe.

Also, I noticed glxosd is available for Arch:
https://aur.archlinux.org/packages/glxosd/
I don't know how anything about its maintainers there, but you might consider linking to that as well.

Thanks.

**Comment by nickguletskii** [comment]
Thank you very much for this. With version 1 and 2 I had a lot of trouble with packaging for Ubuntu and Debian, but with the simplifications that are coming with version 3 I will pay more attention to other distros.

**Comment by kparal** [comment]
I have updated Fedora Copr with latest code from `master`.

I also noticed `glxosd` is now in OpenSUSE in one of the unofficial repositories:
http://software.opensuse.org/package/glxosd
But I'm not sure how you enable those (but just the link might be sufficient for most opensuse users).

**Comment by nickguletskii** [comment]
By the way, I haven't updated master to version 3.2.1 yet because the packages are still building and I want to test the changes before releasing.

**Comment by nickguletskii** [comment]
I am going to add the instructions to the website in a few hours. Thank you very much!

**Comment by kparal** [comment]
Thanks. 

(Off topic, but you might want to remove `-b v3` from the `git clone` command in under `Compile from source` section. I think that's outdated now.)

**Comment by nickguletskii** [comment]
You are right, thank you.
