### ISSUE TITLE
don't print empty libsensors values

### ISSUE THREAD

**Issue by kparal** [nickguletskii/GLXOSD#67]
Hello, this is how glxosd looks for me by default:
![glxgears](https://cloud.githubusercontent.com/assets/755451/13333002/ee467894-dc04-11e5-9065-c397c40a02f6.png)

I know I can use `libsensors_chip_feature_filter` to filter out all those useless empty libsensors values, but it requires manual work and it also requires the user to know regular expressions. Why not simply avoid printing libsensors items which have empty values? It can stay configurable for power users, if they have some use for it (but I don't really know what).

What I don't really understand is why some of those values are empty, because they are printed when I run `sensors` in terminal:
```
$ sensors
acpitz-virtual-0
Adapter: Virtual device
temp1:        +27.8°C  (crit = +105.0°C)
temp2:        +29.8°C  (crit = +105.0°C)

radeon-pci-0100
Adapter: PCI adapter
temp1:        +38.0°C  (crit = +120.0°C, hyst = +90.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:  +35.0°C  (high = +80.0°C, crit = +100.0°C)
Core 0:         +34.0°C  (high = +80.0°C, crit = +100.0°C)
Core 1:         +35.0°C  (high = +80.0°C, crit = +100.0°C)
Core 2:         +34.0°C  (high = +80.0°C, crit = +100.0°C)
Core 3:         +34.0°C  (high = +80.0°C, crit = +100.0°C)

it8728-isa-0a30
Adapter: ISA adapter
in0:          +0.10 V  (min =  +0.00 V, max =  +3.06 V)
in1:          +1.96 V  (min =  +0.00 V, max =  +3.06 V)
in2:          +2.00 V  (min =  +0.00 V, max =  +3.06 V)
in3:          +2.04 V  (min =  +0.00 V, max =  +3.06 V)
in4:          +0.01 V  (min =  +0.00 V, max =  +3.06 V)
in5:          +1.75 V  (min =  +0.00 V, max =  +3.06 V)
in6:          +1.49 V  (min =  +0.00 V, max =  +3.06 V)
3VSB:         +3.38 V  (min =  +0.00 V, max =  +6.12 V)
Vbat:         +3.17 V  
fan1:         719 RPM  (min =   10 RPM)
fan2:           0 RPM  (min =    0 RPM)
fan3:           0 RPM  (min =    0 RPM)
fan4:           0 RPM  (min =    0 RPM)
fan5:           0 RPM  (min =    0 RPM)
temp1:        +30.0°C  (low  =  +0.0°C, high = +60.0°C)  sensor = thermistor
temp2:        +25.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermistor
temp3:        +27.0°C  (low  =  +0.0°C, high = +70.0°C)  sensor = Intel PECI
intrusion0:  ALARM
```
I assume you only print values which have `°C` in them (which is a reasonable default). In that case, again, why not hide the rest?

(I would be actually interested to see `fan1` in the output, so it would be nice to not only print values containing `°C` by default, but also values containing `RPM` and a non-zero number, and hide the rest).

glxosd 20160210git7f0886e

**Comment by nickguletskii** [comment]
Could you please confirm that GLXOSD v3 filters out empty sensors chips?

**Comment by kparal** [comment]
I'll test. Could you please clarify whether I should use latest `development` or `master` branch and what's your intended approach with these branches? I assumed `master` is latest stable code, and `development` is latest unstable code (therefore always same or newer than `master`), but right now `development` seems to be diverged from `master`. Will that get adjusted? If I want to package the latest unstable version, which branch should I use in the future? Thanks.

**Comment by nickguletskii** [comment]
Thank you very much. I forgot to update the development branch because I was using a separate version branch for v3. I will be tagging releases in master too.
