### ISSUE TITLE
support voglperf csv files in frame log analyser

### ISSUE THREAD

**Issue by kparal** [nickguletskii/GLXOSD#68]
Your [frame log analyser](https://glxosd.nickguletskii.com/analyse.html) is an awesome tool. You could perhaps also support csv files that [voglperf](https://github.com/ValveSoftware/voglperf) creates?

Example:
[voglperf.gameid222140.2016_03_02-22_07_36.csv.zip](https://github.com/nickguletskii/GLXOSD/files/157307/voglperf.gameid222140.2016_03_02-22_07_36.csv.zip)

**Comment by nickguletskii** [comment]
The frame log analyser for version 3 supports voglperf files now.

**Comment by kparal** [comment]
Thanks!
