### ISSUE TITLE
GLXOSD primusrun seg faults or fails to load any of the libraries

### ISSUE THREAD

**Issue by nhidog** [nickguletskii/GLXOSD#82]
This is on Ubuntu 16.04 
glxosd glxgears works
primusrun glxgears works

glxosd primusrun glxgears seg faults or fails to load any of the libraries
`user@XPS15:~$ bash -x glxosd primusrun glxgears
+ OPTIND=1
+ INJECT_STEAM_OVERLAY=false
+ STEAM_PATH=/home/user/.local/share/Steam
+ GLXOSD_SCRIPTS_ROOT=/usr/share/glxosd//
+ GLXOSD_ADDITIONAL_CONFIG_LOCATION=
+ :
+ case "$1" in
+ break
+ STEAM_OVERLAY_LIB_PATHS=
+ STEAM_OVERLAY_LIBS=
+ '[' false = true ']'
+ GLXOSD_LIBRARY_PATH_I386=/usr//lib/i386-linux-gnu//glxosd/
+ GLXOSD_LIBRARY_PATH_AMD64=/usr//lib/x86_64-linux-gnu//glxosd/
+ export LD_LIBRARY_PATH=:/usr//lib/i386-linux-gnu//glxosd/:/usr//lib/x86_64-linux-gnu//glxosd/:
+ LD_LIBRARY_PATH=:/usr//lib/i386-linux-gnu//glxosd/:/usr//lib/x86_64-linux-gnu//glxosd/:
+ export LD_PRELOAD=::libglxosd-elfhacks.so:libglxosd-glinject.so:
+ LD_PRELOAD=::libglxosd-elfhacks.so:libglxosd-glinject.so:
+ export GLXOSD_SCRIPTS_ROOT
+ export GLXOSD_ADDITIONAL_CONFIG_LOCATION
+ primusrun glxgears
primus: fatal: failed to load any of the libraries: /usr/lib/nvidia-361/libGL.so.1:/usr/lib32/nvidia-361/libGL.so.1
libGLX.so.0: cannot open shared object file: No such file or directory
/usr/lib32/nvidia-361/libGL.so.1: wrong ELF class: ELFCLASS32`

`user@XPS15:~$ bash -x glxosd primusrun glxgears
+ OPTIND=1
+ INJECT_STEAM_OVERLAY=false
+ STEAM_PATH=/home/user/.local/share/Steam
+ GLXOSD_SCRIPTS_ROOT=/usr/share/glxosd//
+ GLXOSD_ADDITIONAL_CONFIG_LOCATION=
+ :
+ case "$1" in
+ break
+ STEAM_OVERLAY_LIB_PATHS=
+ STEAM_OVERLAY_LIBS=
+ '[' false = true ']'
+ GLXOSD_LIBRARY_PATH_I386=/usr//lib/i386-linux-gnu//glxosd/
+ GLXOSD_LIBRARY_PATH_AMD64=/usr//lib/x86_64-linux-gnu//glxosd/
+ export LD_LIBRARY_PATH=:/usr//lib/i386-linux-gnu//glxosd/:/usr//lib/x86_64-linux-gnu//glxosd/:
+ LD_LIBRARY_PATH=:/usr//lib/i386-linux-gnu//glxosd/:/usr//lib/x86_64-linux-gnu//glxosd/:
+ export LD_PRELOAD=::libglxosd-elfhacks.so:libglxosd-glinject.so:
+ LD_PRELOAD=::libglxosd-elfhacks.so:libglxosd-glinject.so:
+ export GLXOSD_SCRIPTS_ROOT
+ export GLXOSD_ADDITIONAL_CONFIG_LOCATION
+ primusrun glxgears
/usr/bin/glxosd: line 60:   583 Segmentation fault      (core dumped) "$@"`

**Comment by nickguletskii** [comment]
I don't have an NVIDIA prime system to test on, but I think the solution would be to integrate primusrun functionality into the launcher directly. I'll look into it soon.

**Comment by nhidog** [comment]
Did lots of uninstall/reinstall bumblebee bumblebee-nvidia primus and various nvidia-361, nvidia-364, nvidia-367 trying out vulkan and somehow I ended up fixing this issue going back to nvidia-361.
