### ISSUE TITLE
Improvement: use exec "$@"

### ISSUE THREAD

**Issue by XenonPK** [nickguletskii/GLXOSD#89]
After using glxosd for some time, I started tinkering a bit with it and noticed the way the process is launched by the launcher is using fork() exec(), which leaves a dangling bash process while the application is running.
This is unnecessary and can be fixed by launching the application with:
exec "$@"
instead of : 
"$@"
It's not a big deal BUT it should be fixed.

**Comment by nickguletskii** [comment]
Since this is a minor fix I will include it in a release with other features.

**Comment by nickguletskii** [comment]
Thank you for reporting this!

**Comment by XenonPK** [comment]
No problem, I actually packaged glxosd for [openSUSE](https://build.opensuse.org/package/show?project=home%3Axenonpk&package=glxosd) and used sed to add it in the install section.
Then I figured it's better for everyone if I report it upstream.
