### ISSUE TITLE
New Feature: Allow framerate limiter

### ISSUE THREAD

**Issue by XenonPK** [nickguletskii/GLXOSD#90]
Before finding out about glxosd, I was using [libstrangle](https://github.com/torkel104/libstrangle) to limit my fps , now your function overrides coincide with the ones libstrangle is using, specifically glXSwapBuffers.
Trying to LD_PRELOAD both libraries incurs in segmentation fault.
Seeing as glxosd already has support for shortcuts , why not add another shortcut for capping/uncapping the framerate , and use an algorithm similar to the one used in libstrangle?
I know this may be a bit more work, but I think it would be a feature very much appreciated by people with optimus laptops using nvidia-prime ( there is no way to do vsync and/or limit the framerate in any way without external tools).
The way it stands now, I can either cap the framerate or get the osd, not both.
Maybe in the next major version?

**Comment by nickguletskii** [comment]
Thanks for reminding me about this, I planned to add this after the initial release but ended up forgetting about it.

I don't have much time at the moment (it's mostly the packaging process that is time consuming), but I will implement it once I get the chance.
