### ISSUE TITLE
Add openSUSE to install instructions

### ISSUE THREAD

**Issue by XenonPK** [nickguletskii/GLXOSD#99]
glxosd is now included in the default OpenSUSE repositories, as you can see from this [request](https://build.opensuse.org/request/show/455010).
It is already available to install on tumbleweed, and for earlier versions, it is maintained in the [games:tools](https://build.opensuse.org/package/show/games:tools/glxosd) project.
For tumbleweed users it's as simple as doing "sudo zypper install glxosd", for others, the install instructions are available [here](https://software.opensuse.org/download.html?project=games%3Atools&package=glxosd).
Also, take a look at  this [patch](https://build.opensuse.org/package/view_file/games:tools/glxosd/64bit_portability.patch?expand=1), it fixes a 64 bit portability error due to a missing include. Please consider updating the installation instructions [page](https://glxosd.nickguletskii.com/install/).

**Comment by nickguletskii** [comment]
Thank you for packaging GLXOSD for OpenSUSE and for the patch! I will incorporate the patch and add the install instructions once I find a spare hour or two.

Meanwhile, could you please provide the instructions to install both the 32-bit and 64-bit versions on 64-bit systems (assuming that is possible on OpenSUSE)?

Once again, thank you for the contributions!

**Comment by XenonPK** [comment]
The package with the 32 bit libraries is glxosd-32bit.

To install everything (all the plugins too) in a 64 bit system:

zypper install glxosd glxosd-32bit glxosd-nvidia-plugin

To avoid issues, you should include all the plugins in the default instructions (I subdivided them for power users that can handle the lua config files and don't have nvidia hardware).

For 32bit systems use the same command, excluding the glxosd-32bit package.

**Comment by nickguletskii** [comment]
Thank you very much! I'll close this issue once the patch is live and the site is updated.
